### ISSUE TITLE
bezpieczniejsze umieszczenie kluczy PayU

### ISSUE THREAD

**Issue by ghost** [ronin/payu#10]
Cześć!

Gem działa bardzo dobrze, ale mam problem z bezpieczeństwem, a mianowicie chciałbym trzymać klucze (pos_id, pos_auth_key, key1, key2) w zmiennych ENV zamiast bezpośrednio w pliku payu.yml. Chciałem zrobić to gemem Figaro, ale niestety podczas startu serwera aplikacja wyrzuca błąd walidacji (kod jaki stosuję poniżej). Czy znasz rozwiązanie tego problemu, jak trzymać klucze bezpiecznej, ale wciąż korzystać np. z Pay['main'] i nie przerabiać/nadpisywać kodu gema?

//payu.rb
Payu.load_pos_from_yaml(Rails.root.join('config', 'payu.yml.erb'))

//payu.yml.erb
main:
  pos_id: <%= ENV['payu_umedpoznan_pos_id'] %>

**Comment by ronin** [comment]
Możesz stworzyć Pos ręcznie z danych w ENV a potem go dodać do listy:

```ruby
pos = Payu::Pos.new :pos_id => ENV['payu_umedpoznan_pos_id'], :pos_auth_key => 'xxxxx', :key1 => 'xxxxxxxx', :key2 => 'xxxxxxxx', :add_signature => true
Payu.add_pos('main', pos)
```

**Comment by ghost** [comment]
Cześć! Dzięki za szybką odpowiedź :)) Spróbuję tej metody!

Zanim zamkniemy wątek mam jeszcze jedno pytanie, czy stosując tę metodę poniższa funkcja będzie działać (zwrotka report w PayuController)? Czy może wystarczy zastąpić Payu['main'] np. ENV['payu_main_pos_id'] zdefiniowaną przez Figaro?

response = Payu['main'].get params[:session_id]

Z góry przepraszam jeśli zadaję zbyt podstawowe pytanie, ale pierwszy raz integruję bramkę z aplikacją :)

**Comment by ronin** [comment]
Powinna działać :) Oczywiście ten kod, który podałem musisz dodać w `initializers`, żeby pos został stworzony zanim zaczniesz go używać. Ta zamiana między `Payu` a `ENV` nie zadziała, bo takie metody jak `get` są wywoływane na obiekcie `Payu::Pos`.

**Comment by ghost** [comment]
OK, dziękuję! Zdaje się, że rozumiem, ale jak będę miał większy problem to skontaktuję się w prywatnej wiadomości. Wątek mam nadzieję, że komuś się jeszcze przyda.
