### ISSUE TITLE
przekierowanie do PayU z Controllera "Orders", a nie odrębnego formularza

### ISSUE THREAD

**Issue by ghost** [ronin/payu#11]
Cześć ponownie!

Michał, mam będę dozgonnie wdzięczny za jeszcze jedną wskazówkę. 

Staram się zrobić formularz gdzie User po wypełnieniu danych zamówienia / do faktury jest od razu przekierowany z controllera Orders do strony PayU linkiem ze wszystkimi wymaganymi parametrami (po udanym utworzeniu Order'a oczywiście). Czy korzystając z Twojego gema jest możliwość odpowiedniej konstrukcji akcji Orders#create i czy mógłbyś podrzucić jakąś wskazówkę jak to zrobić? Czy może sugerujesz lepiej żeby zrobić osobny widok (np. Orders#payment) z proponowanym w dokumentacji formularzem?

Dodam jeszcze, że znalazłem wątek na SO gdzie pada stwierdzenie, że nie można zrobić redirecta POST z controllera (http://stackoverflow.com/questions/10614502/post-and-redirect-to-external-site-from-rails-controller), jednak czekam na Twoją opinię :)

```
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.buyer = current_user
    @order.total_price = 100
    @order.status = 1
    if @order.save

      pos = Payu::Pos.new pos_id: Payu['test'].pos_id,
      pos_auth_key: Payu['test'].pos_auth_key,
      key1: Payu['test'].key1,
      key2: Payu['test'].key2,
      add_signature: true

      transaction = pos.new_transaction(first_name: 'John',
      last_name: 'Doe',
      email: 'john.doe@example.org',
      client_ip: '1.2.3.4',
      amount: 10000,
      desc: 'Transaction description')

     # Net::HTTP ?????? 
    else
      render :new
    end
  end

private

def order_params
  params.require(:order).permit(:buyer_type, :buyer_name, :buyer_street,
    :buyer_city, :buyer_postal_code, :buyer_tax_no)
end

end
```

<img width="1194" alt="zrzut ekranu 2017-01-02 o 16 21 08" src="https://cloud.githubusercontent.com/assets/44981/21591842/33c51922-d108-11e6-8ffe-3b135777bc54.png">

**Comment by ronin** [comment]
SO ma rację, nie da się zrobić redirect-a POST :) Możesz zrobić formularz tak jak w dokumentacji, ale bez przycisku "Zapłać" i wysłać ten formularz automatycznie przez javascript zaraz po załadowaniu się strony. Najlepiej jakby ta strona była taka bardzo surowa, żeby się szybko ładowała.

```
<%= form_tag(@transaction.new_url, id: "payu-form") do %>
  <%= payu_hidden_fields(@transaction) %>
<% end %>
<script type="text/javascript">
  // Jak nie używasz jquery to jakoś inaczej to musisz zapisać
  $(function() {
    $("#payu-form").submit();
  });
</script>
```

Oczywiście i tak sugeruję, żebyś zaimplementował dedykowaną stronę, z której będzie można wykonać płatność. Klient zawsze może przerwać proces gdzieś w trakcie i dobrze jakby mógł wrócić do swojej płatności.

**Comment by ghost** [comment]
Michał, wielkie dzięki za wyczerpującą odpowiedź - tutaj wszystko jest dla mnie jasne :) Cieszę się, że stoisz na posterunku tego gema bo początkowo myślałem, że już nie jest rozwijany i nie jest aktualny, ale myliłem się. Zrobię tak, jak mówisz, czyli zbuduję osobą stronę z wykonaniem płatności bo zgadzam się z Twoimi argumentami, że ma to większy sens z punktu widzenia reaktywacji przerwanych płatności.
