### ISSUE TITLE
Payu::PosNotFound 

### ISSUE THREAD

**Issue by paako-chan** [ronin/payu#3]
Niestety, ale dostaję taki error Payu::PosNotFound (Payu::PosNotFound):app/controllers/payu_controller.rb w linijce:

```
response = Payu['main'].get params[:session_id]
```

Będę wdzięczna za pomoc :)

**Comment by ronin** [comment]
"main" to nazwa nadana przez Ciebie w pliku payu.yml

Np. dla konfiguracji poniżej trzeba się odwoływać przez Payu['bank']

```
bank:
  pos_id: 12345
  ...
```

**Comment by paako-chan** [comment]
ślicznie dziękuję za pomoc :)
