### ISSUE TITLE
After @pos.new_transaction nothing is called

### ISSUE THREAD

**Issue by Sacristan** [ronin/payu#6]
params_for_payu_pos = {order_id: 1, first_name: "ME", last_name: "Dummy", email: "me@me.com", client_ip: request.remote_ip, amount: @amount, desc: message, language: "pl"}

@payu_payment_helper = @pos.new_transaction(params_for_payu_pos)

render json: params_for_payu_pos

---

Problems:
render json: params_for_payu_pos IS Not called;
layout and action view is rendered neither.

Basically everything is not called anymore

The result is as if there would be simply called render nothing: true  in new_transaction

Controller: http://pastebin.com/QXsJDRYu
Configuration: http://pastebin.com/gRqFtEq8

Rails v 4.2.0
Ruby v 2.2.0

Is there a known problem ?

**Comment by ronin** [comment]
For me this looks like some problem with your application and not like a bug in this gem. Attached code is also not very clear. What it is supposed to do. Why do you create @payu_payment_helper variable if you don't use it?

**Comment by Sacristan** [comment]
This should throw to PayU payment_systems index view.

What i did there: 
- we are having a working solution of PayU (Rails 4.1, Ruby 2.0) and brought this to our new platform, but it did not work on our new plaftorm, because  after new_transaction is called ON Pos next lines are never called (not even rails stuff); 
- So i dumbed down the solution to version what ur seeing (added dummy data to new_transaction params) -> still the same problem;
-  All of our development team reviewed code AND all as one said that something is wrong with new_transaction command - it should return from it, but never does.

You have Payu::Transaction class is there by any way chance that Rails somehow confuses Payu::Transaction with ActiveRecord::Transaction. I no longer use Transaction model, but have replaced it with Payment in all new platforms, cause Rails confuses Transaction model with ActiveRecord::Transaction. The old platform where PayU is working like a charm - has Transform model on it and no Rails confusion with ActiveRecord::Transaction .

It is supposed to use @payu_payment_helper in new payu view. But this is never rendered. Nothing is called after new_transaction -> all action lines should be called.

<html>
  <body>
  <body onload="document.swdForm.submit();" style="display:none;">
      <%= form_tag(@payu_payment_helper.new_url, name: "swdForm") do %>
        <%= payu_hidden_fields(@payu_payment_helper) %>
      <% end %>
  </body>
</html>

**Comment by Sacristan** [comment]
``` ruby
def new
    params_for_payu_pos = {order_id: 123456, first_name: "ME", last_name: "Dummy", email: "me@me.me", client_ip: request.remote_ip, amount: @amount, desc: "????", language: "pl"}
    @payu_payment_helper = @pos.new_transaction(params_for_payu_pos)
    render text: "ThisShouldBeDisplayedButIsNot"
end
```

Are there any hidden renders or redirects in new_transaction flow?

**Comment by Epigene** [comment]
Yup, the ^ "dumbed down" version mysteriously stops execution on the `@payu_payment_helper =` line.

Maybe ruby version incompatability?

**Comment by Epigene** [comment]
Here is my try:

``` ruby
def new
  @transaction = Payu[:bank].new_transaction({
    amount: 10,
    order_id: 123,
    language: "pl",
    first_name: "Lorem",
    last_name: "Ipsum",
    email: "epigene@epigene.org",
    client_ip: request.remote_ip,
    desc: "New PayU transaction"
  })

  render json: @transaction
end
```

@transaction object does not get rendered (any ol' plain JSON does)

**Comment by Sacristan** [comment]
And if You put something else besides @transaction ? It is rendered / called ? 

for me neither puts, neither render (actually nothing is called after Payu::Pos.new_transaction method.

**Comment by ronin** [comment]
new_transaction method doesn't render anything, it just creates transaction object. I've added simple controller to my other project written in ruby 2.2.0 and rails 4.2.0 and have no problems.

Maybe please try your code on new rails app.

**Comment by ronin** [comment]
You can also test new_transaction method in rails console and see what is returned

**Comment by Epigene** [comment]
Found it! email parameter is required.
If `@pos.new_transaction(hash_with_no_email_parameter)`, there is an argument error that weirdly hangs code execution.
Pass the argument correctly and should work.
