### ISSUE TITLE
blad 103

### ISSUE THREAD

**Issue by przemkow** [ronin/payu#7]
Cześć, mam problem z integracja poprzez waszego gema, w celach edukacyjnych próbowałem podpiąć testowe płatności do apki i niestety nie mam pojęcia dlaczego payu wywali mi błąd 103 (brak lub błędna wartość parametru sig), parametr znajduje się w formularzu więc pewnie jest źle wyliczony, pytanie tylko dlaczego.
Kod jest raczej standardowy i wielkiej filozofii w nim nie ma. W kontrolerze mam:
pos = Payu::Pos.new(:pos_id => '145227', :pos_auth_key => 'abcdefghijk', :key1 => 'xxxxxxxx', :key2 => '13a980d4f851f3d9a1cfc792fb1f5e50', :add_signature => true)
@transaction = pos.new_transaction(:first_name => 'John', :last_name => 'Doe', :email => 'john.doe@example.org', :client_ip => '127.0.0.1', :amount => 10000, desc: 'sth')

w widoku to co podaliście w readme. 
Macie jakieś pomysły na to co robię źle? próbowałem różnych kombinacji danych testowych, szukałem rozwiązania w dokumentacji do payu ale najwyraźniej coś za każdym razem musiałem przeoczyć. Z góry wielkie dzięki za pomoc! Pozdrawiam :)

**Comment by ronin** [comment]
Możesz pokazać więcej kodu? Tzn chodzi mi o kod kontrolera, który generuje akcję oraz widok formularz płatności.

**Comment by przemkow** [comment]
Jasne, kod kontrolera oraz widoku wygląda następująco:
https://gist.github.com/przemkow/bc1cc30384d261295c02
pos_auth_key oraz key1 są ustawione na te które były podane przez was domyślnie ponieważ te parametry dla testowego punktu sprzedaży nie są udostępniane.

**Comment by ronin** [comment]
Payu udostępnia wszystkie klucze dla testowych punktów płatności. Właściwie to nie ma czegoś takiego jak testowe punkty płatności. To jest normalny punkt płatności, który ma włączone testowe płatności. Musisz sobie skonfigurować normalny punkt i wpisać wszystkie poprawne klucze.

**Comment by przemkow** [comment]
mówiąc testowe punkty płatności miałem na myśli to co podają tutaj http://developers.payu.com/pl/restapi.html na końcu punktu 1. Konta na payu niestety założyć oficjalnie nie mogę ponieważ nie posiadam zarejestrowanej firmy której dane mógłbym wykorzystać. Dzięki za pomoc, bede próbował z tym walczyć jeszcze w jakiś inny sposób :)
