### ISSUE TITLE
Błąd 201

### ISSUE THREAD

**Issue by michu88** [ronin/payu#9]
Hej,
Mam problem z użyciem waszego rozwiązania. Po przesłaniu formularza przekierowuje mnie na stronę payu i dostaję komunikat błędu 201. Jest to 201 inny chwilowy błąd bazy danych.

Controller:
`    pos = Payu['bank']

```
@ip = request.remote_ip
@random_hex = random_string = SecureRandom.hex

@transaction = pos.new_transaction(
    :first_name => 'Michal',
    :last_name => 'Kroszka',
    :email => 'mkroszka@myrpg.pl',
    :client_ip => @ip,
    :amount => 10000,
    :desc => 'Transaction description'
)`
```

View:
`<%= form_tag(@transaction.new_url) do %>
    <%= payu_hidden_fields(@transaction) %>
    <%= submit_tag 'Pay' %>
<% end %>`

Proszę o info co może być nie tak.

**Comment by ronin** [comment]
@michu88 Wygląda to jak błąd po stronie Payu, sam opis błędu to sugeruje. Czy problem cały czas się powtarza? Próbowałeś uzyskać pomoc po stronie Payu?

**Comment by michu88** [comment]
@ronin Po kontakcie z PayU wszystko się wyjaśniło, musiałem zmienić bramę i działa bez zarzutów. Wątek można zamknąć i dziękuję za szybkie zainteresowanie się sprawą.
